import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderSection from "@/components/common/header";
import FooterSection from "@/components/common/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased text-[var(--text-primary)] w-full min-h-screen bg-[#FFFDF0]`}
      >
        <div className="w-full h-[10vh]">
          <HeaderSection/>
        </div>
        <div className="w-full ">
          {children}
        </div>
        <div className="w-full h-[]">
          <FooterSection/>
        </div>
      </body>
    </html>
  );
}
